#!/bin/bash
echo "Stop service rpass..."
/bin/systemctl stop rpass.service > /dev/null 2>&1
echo "Configuration systemd..."
/bin/systemctl disable rpass.service > /dev/null 2>&1
/bin/systemctl daemon-reload
